

# Site settings

title: eQuanta
email: euripes@gmail.com
description: Diligentia laborat omni silvae et orb maria
baseurl: "http://leroy1977.github.io" 
url: "http://leroy1977.github.io"

github_username: eQuanta.env

# Build settings
markdown: kramdown
permalink: /:title/
